# Production values for Reporter API.
# This is a YAML-formatted file.
# Declare variables to be passed into the template.

env:
  ALLOW_NEGATIVE_ADVANCE: false
  CORS_ORIGIN: https://reporter.0x.se
  DATABASE_VERSION: v4
  MAIL_ENABLED: true
  MAIL_FROM: reporter@0x.se
  SPRING_LOG_LEVEL: INFO
  SUCCESS_URL: https://reporter.0x.se/login/success

envSecretRef: reporter-api

replicas: 2
ingress:
  enabled: true
  hosts:
    - reporter-api.0x.se
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: reporter-api-prod
      hosts:
        - reporter-api.0x.se
