# Default values for Reporter API
# This is a YAML-formatted file.
# Declare variables to be passed into the template.

## Number of pods to run concurrently in the replica set
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#replicas
##
replicas: 1

## Reporter API Docker image
##
image: gcr.io/zero-plus-x/reporter-api:latest

## Service
## ref: https://kubernetes.io/docs/concepts/services-networking/service/
##
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080

## Ingress for Services
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts: []
  #hosts:
  #  - reporter-api-staging.0x.se
  labels: {}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/acme-challenge-type: dns01
    cert-manager.io/acme-dns01-provider: clouddns
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls: []
  #tls:
  #  - secretName: reporter-api-staging
  #    hosts:
  #      - reporter-api-staging.0x.se


## Define envs
## ref: https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
##
env: {}

## Define envs from secret
## ref: https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#configure-all-key-value-pairs-in-a-secret-as-container-environment-variables
##
#envSecretRef: secretRef

## Strategy used to replace old Pods by new ones
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
##
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0 # replicas-1 = 0

## Pod Health Checking
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
##
livenessProbe:
  httpGet:
    path: /api/health/liveliness
    port: 8080
  initialDelaySeconds: 90
  timeoutSeconds: 5
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /api/health/liveliness
    port: 8080
  initialDelaySeconds: 90
  timeoutSeconds: 5
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3

## Compute Resources for Containers
## ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
##
resources: {}

## Annotations for pod assignment
## ref: https://kubernetes.io/docs/reference/labels-annotations-taints/
#       https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
annotations: {}

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Affinity for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}
