# Default values for java-webapp
# This is a YAML-formatted file.
# Declare variables to be passed into the template.

## Override the chart name
##
nameOverride: ""

## Number of pods to run concurrently in the replica set
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#replicas
##
replicas: 1

## Java Docker image
##
image: <repo/org/image:tag>

## Service
## ref: https://kubernetes.io/docs/concepts/services-networking/service/
##
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  labels: {}
  annotations: {}

## Ingress for Services
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  enabled: false
  hosts:
  - chart-example.local
  labels: {}
  annotations: {}
    # kubernetes.io/ingress.class: nginx # or e.g. traefik
    # kubernetes.io/tls-acme: "true"
  tls: []
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

## Define envs
## ref: https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
##
env: {}

## Define envs from secret
## ref: https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#configure-all-key-value-pairs-in-a-secret-as-container-environment-variables
##
envSecretRef: "" # set to name of secret

## Secret files
## ref: https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod
##
secretFileRefs: []

## Strategy used to replace old Pods by new ones
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
##
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0 # replicas-1 = 0

## Pod Health Checking
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
##
livenessProbe:
  httpGet:
    path: /api/health/liveliness
    port: 8080
  initialDelaySeconds: 90
  timeoutSeconds: 5
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /api/health/liveliness
    port: 8080
  initialDelaySeconds: 90
  timeoutSeconds: 5
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3

## Compute Resources for Containers
## ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
##
resources: {}

## Annotations for pod assignment
## ref: https://kubernetes.io/docs/reference/labels-annotations-taints/
#       https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
annotations: {}

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Affinity for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}
