---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: zeroplusx/kube-workspace:latest
  commands:
  - for d in */ ; do (helm lint --strict $d) || exit 1; done || exit 1
  - for d in */ ; do (helm package --save=false $d) || exit 1; done || exit 1
  - curl -#SLo index_latest.yaml http://charts.0x.se/index.yaml
  - helm repo index . --merge index_latest.yaml --url http://charts.0x.se
  - mkdir repo && mv index.yaml repo/ && mv *.tgz repo/

- name: release
  pull: always
  image: google/cloud-sdk:alpine
  commands:
  - echo $GCLOUD_KEY > /tmp/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file /tmp/gcloud-service-key.json --quiet
  - gcloud config set project zero-plus-x
  - gsutil -m rsync -R repo/ gs://charts.0x.se
  - gsutil -m setmeta -r -h "Cache-Control:public, max-age=60" gs://charts.0x.se/*
  environment:
    GCLOUD_KEY:
      from_secret: gcloud_key
  when:
    branch:
    - master
    event:
    - push

trigger:
  branch:
  - master
  event:
  - pull_request
  - push

...
