apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "java-webapp.fullname" . }}
  labels:
    app: {{ template "java-webapp.name" . }}
    chart: {{ template "java-webapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
{{- with .Values.updateStrategy }}
  strategy:
{{ toYaml . | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      app: {{ template "java-webapp.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "java-webapp.name" . }}
        chart: {{ template "java-webapp.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
{{- with .Values.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          {{- if .Values.env }}
          env:
          {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.envSecretRef }}
          envFrom:
          - secretRef:
              name: {{ .Values.envSecretRef }}
          {{- end }}
        {{- if .Values.secretFileRefs }}
          volumeMounts:
          {{- range $secret := .Values.secretFileRefs }}
          - name: {{ $secret }}
            mountPath: "/etc/secrets"
            readOnly: true
          {{- end -}}
        {{- end }}
          ports:
          - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.secretFileRefs }}
      volumes:
      {{- range $secret := .Values.secretFileRefs }}
      - name: {{ $secret }}
        secret:
          secretName: {{ $secret }}
      {{- end -}}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
