apiVersion: v1
kind: Service
metadata:
  name: {{ template "java-webapp.fullname" . }}
  labels:
    app: {{ template "java-webapp.name" . }}
    chart: {{ template "java-webapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ template "java-webapp.fullname" . }}
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "java-webapp.name" . }}
    release: {{ .Release.Name }}
